name: Publish
on:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CMAKE_OSX_ARCHITECTURES: "arm64;x86_64"
          MACOSX_DEPLOYMENT_TARGET: "10.14"
          CIBW_ARCHS_MACOS: x86_64 universal2

      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPi
    needs:
      - build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
