name: Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/builds.yaml'
      - '.github/workflows/docs.yaml'
      - '*.md'
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Build
        run: |
          mkdir -p build
          cmake -B build -DBUILD_PYTHON=ON -DBUILD_DOCS=ON -DBUILD_TESTING=ON
          # symbolic needs to be in the virtual environment.
          pipenv run pip install -e .

      - name: Test
        run: |
          cd build
          ctest --output-on-failure
